### ISSUE TITLE
Specify a pull request structure for user content

### ISSUE THREAD

**Issue by miyoyo** [flutter-showcase/flutter-showcase#1]
We have to specify what folders and names to use to allow users to push their content via pull requests

**Comment by Raatty** [comment]
Could have like one folder called user_content or something then inside people put a folder that matches their user name and put their dart files in there?

**Comment by miyoyo** [comment]
Maybe use compile time generation?

**Comment by GroovinChip** [comment]
I was thinking that when we clone the repo we could make our own projects inside a user_content folder with a subfolder for our usernames and our projects would go in our own folder

**Comment by miyoyo** [comment]
* user_content/
  * Username/
    * Project 1/
      * lib/...
      * assets/...
    * Project 2/
      * lib/...
      * assets/...

Would this make sense?

**Comment by GroovinChip** [comment]
Yes

**Comment by Raatty** [comment]
Yup that's what I was thinking kind of, it makes sure one person's code hopefully doesn't affect the rest

**Comment by miyoyo** [comment]
Alright, since we're probably going towards preprocessing, I'm thinking about having a section in pubspec.yaml that describes the app to flutter-showcase

```yaml
flutter_showcase:
  name: "My awesome project"
  description: "I made this great animation
  Check it out!"
  author: "Test Tester"
  project-url: "https://github.com/testtester/animate-things"
  type: "animation"
```

**Comment by agavram** [comment]
I like the idea, but how exactly would we go about preprocessing the pubspec.yaml?

**Comment by miyoyo** [comment]
@darthdie Has put together a preprocessor (and a search too!), as well as updated the format

A tag system will be provided, alongside the categories, here's the potential final format
```yaml
flutter_showcase:
  name: "SLYCK Animations"
  description: "Made of pure grease."
  author: "John Travolta"
  project-url: "https://github.com/greaser/slyck"
  type: "animation"
  tags:
    - slicked back hair
    - the 80s
```
